spring.application.name=baozistore

# 1. Ativa e instancia o banco de dados H2 na memória do projeto
spring.datasource.url=jdbc:h2:mem:baozidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Configura o Spring para criar as tabelas automaticamente com base no seu @Entity
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# 3. Libera um painel visual do banco no navegador para você ver as tabelas
spring.h2.console.enabled=true
